version: '3.8'

services:
  temporal:
    image: temporalio/auto-setup:1.22.3
    ports:
      - "7233:7233"
      - "7234:7234"
      - "7235:7235"
    environment:
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml
      - ENABLE_ES=false
      - DB=postgresql
      - DBNAME=temporal
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=postgresql
    depends_on:
      - postgresql

  postgresql:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_DB=temporal
    volumes:
      - postgresql-data:/var/lib/postgresql/data

volumes:
  postgresql-data: 